#!/usr/bin/env -S uv run --script
# vim: ft=python
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "tomlkit>=0.13.0",
# ]
# ///

from keymap import main


if __name__ == "__main__":
    main()
