font_family GeistMono Nerd Font, JetBrains Mono, Noto Sans Mono
font_size 14
font_features GeistMono Nerd Font +calt +clig +liga +dlig

shell /bin/zsh -l
shell_integration enabled
editor /usr/bin/nvim
allow_remote_control yes


hide_window_decorations no
background_opacity 1.0
confirm_os_window_close 0
window_padding_width 0

cursor_shape underline
cursor_underline_thickness 2.0
cursor_blink_interval 0
cursor_trail 3
cursor_trail_color #a3b4eb

foreground #cdd6f4
background #1e1e2e
cursor #f5e0dc
cursor_text_color #1e1e2e
selection_foreground #cdd6f4
selection_background #45475a

color0 #45475a
color1 #f38ba8
color2 #a6e3a1
color3 #f9e2af
color4 #89b4fa
color5 #cba6f7
color6 #94e2d5
color7 #bac2de
color8 #585b70
color9 #f38ba8
color10 #a6e3a1
color11 #f9e2af
color12 #89b4fa
color13 #cba6f7
color14 #94e2d5
color15 #a6adc8

tab_bar_style powerline
tab_bar_edge top
tab_bar_background #1e1e2e
active_tab_foreground #cdd6f4
active_tab_background #313244
inactive_tab_foreground #585b70
inactive_tab_background #1e1e2e
tab_bar_min_tabs 2

# Generate keymaps via kitty's embedded Python.
# geninclude keymap.py
geninclude config

scrollback_lines 10000
