"$schema" = "https://mise.en.dev/schema/mise.json"

[tools]
bun = "1.3.13"
chezmoi = "2.70.2"
neovim = "0.12.2"
usage = "3.2.1"

[tasks.format-kdl]
run = """
kdlfmt format --kdl-version v1 ./home/dot_config/niri
kdlfmt format --kdl-version v2 ./home/dot_config/zsh/usage
kdlfmt format --kdl-version v1 ./home/dot_config/zellij
"""

[tasks.format-lua]
run = """
luafmt ./home/dot_config/nvim/lua --write
luafmt ./home/dot_config/wezterm --write
"""

[tasks.format]
depends = [
"format-lua", 
"format-kdl"
]
