alias src='clear; exec zsh'
alias ..='cd ..'
alias ...='cd ../..'
alias rmr='rm -r'
alias rmrf='rm -rf'
alias cpr='cp -ri'
alias xhome='cd ~'
alias xconfig='cd $XDG_CONFIG_HOME'
alias xdata='cd $XDG_DATA_HOME'
alias xcode='cd $HOME/ghq/github.com/ggallovalle'
alias xdots='cd $HOME/dotfiles'
alias xgh='cd $HOME/ghq/github.com'

if (( ${+commands[eza]} )); then
  export EZA_STRICT=1
  alias ls='eza --group-directories-first --git-ignore'
  alias la='eza -A --group-directories-first --git-ignore'
  alias laa='eza -A --group-directories-first'
  alias ll='eza -lh --no-user --time-style=iso --group-directories-first --git --git-repos --git-ignore'
  alias lla='eza -lhA --no-user --time-style=iso --group-directories-first --git --git-repos --git-ignore'
  alias llaa='eza -lhA --no-user --time-style=iso --group-directories-first --git --git-repos'
  alias ld='eza -d --git'
  alias lt='eza --git-ignore -TL 3'
  alias lta='eza -ATL 3 --git-ignore'
  alias ltaa='eza -ATL 3'
fi
