#!/usr/bin/env zsh

0="${ZERO:-${${0:#$ZSH_ARGZERO}:-${(%):-%N}}}"
0="${${(M)0:#/*}:-$PWD/$0}"

generated_completions_count=0

typeset -a _usage_files
_usage_files=("${kbroom[ZDOTDIR]}"/usage/*.kdl(N))

for _usage_file in "${_usage_files[@]}"; do
  _complete_this="${${_usage_file:t}:r}"
  _target="${HOME}/.zi/completions/_${_complete_this}"

  _gen_cmd=(usage generate completion zsh "$_complete_this" -f "$_usage_file")

  if (( ${+commands[$_complete_this]} )); then
    print -r -- $'\e[2m$ '"${(j: :)${(q+)_gen_cmd[@]}}"$'\e[0m'

    "${_gen_cmd[@]}" >| "$_target"
    (( generated_completions_count++ ))
  fi
done

if (( generated_completions_count > 0 )); then
  print -r -- "Generated ${generated_completions_count} completions from usage"
fi
