[tools]
bitwarden = "latest"
bun = "1.3.13"
codex = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
"github:EmmyLuaLs/emmylua-analyzer-rust" = "latest"
"github:cargo-bins/cargo-binstall" = "latest"
"github:pamburus/hl" = "latest"
"gitlab:gitlab-org/cli" = "latest"
glow = "latest"
go = "1.26.2"
jq = "latest"
lazygit = "latest"
lua = "latest"
neovim = "latest"
node = "latest"
"npm:@involvex/youtube-music-cli" = "latest"
opencode = "latest"
python = "latest"
rust = "latest"
starship = "latest"
tlrc = "latest"
ttyd = "latest"
typst = "latest"
usage = "latest"
uv = "latest"
vhs = "latest"
yazi = "latest"
yt-dlp = { version = "latest", rename_exe = "yt-dlp" }
zellij = "latest"
zoxide = "latest"
