default:
  just --list

build:
  zig build -Doptimize=ReleaseSmall
  cp zig-out/bin/kbsh $HOME/.local/bin/
  ls -lh $HOME/.local/bin/kbsh | awk '{print $5, $NF}'

clean:
  rm -rf zig-out .zig-cache

test:
  zig build test

run *args:
  zig build run -- {{args}}

fmt:
  zig fmt src/
